version: "3.5"

services:

  bd:
    environment:
      - MYSQL_ROOT_PASSWORD=${PROD_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${PROD_MYSQL_DATABASE}
      - MYSQL_USER=${PROD_MYSQL_USER}
      - MYSQL_PASSWORD=${PROD_MYSQL_PASSWORD}

  web:
    build:
      dockerfile: Dockerfile.prod
    ports:
      - ${PROD_WEB_PORT}:80

  phpmyadmin:
    ports:
      - ${PROD_PHPMYADMIN_PORT}:80
