version: "3.5"

services:

  bd:
    image: mariadb:${MARIADB_VERSION}
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - 3306

  web:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
    depends_on:
      - bd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    depends_on:
      - bd
    environment:
      - PMA_HOST=bd
      - PMA_PORT=3306

volumes:
  mariadb:
